/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RootLayoutRouteImport } from './routes/_rootLayout'
import { Route as AdjustmentSheetRouteImport } from './routes/adjustment-sheet'
import { Route as BasicGridRouteImport } from './routes/basic-grid'
import { Route as GridRouteImport } from './routes/grid'
import { Route as LargeWorkbookRouteImport } from './routes/large-workbook'
import { Route as SessionSheetRouteImport } from './routes/session-sheet'
import { Route as WorkbookClosingRouteImport } from './routes/workbook-closing'
import { Route as WorkbookFormRouteImport } from './routes/workbook-form'
import { Route as WorkbookSheetRouteImport } from './routes/workbook-sheet'
import { Route as RootLayoutAboutRouteImport } from './routes/_rootLayout/about'
import { Route as FilesSplatRouteImport } from './routes/files/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutRoute = RootLayoutRouteImport.update({
  id: '/_rootLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustmentSheetRoute = AdjustmentSheetRouteImport.update({
  id: '/adjustment-sheet',
  path: '/adjustment-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicGridRoute = BasicGridRouteImport.update({
  id: '/basic-grid',
  path: '/basic-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const LargeWorkbookRoute = LargeWorkbookRouteImport.update({
  id: '/large-workbook',
  path: '/large-workbook',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSheetRoute = SessionSheetRouteImport.update({
  id: '/session-sheet',
  path: '/session-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbookClosingRoute = WorkbookClosingRouteImport.update({
  id: '/workbook-closing',
  path: '/workbook-closing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbookFormRoute = WorkbookFormRouteImport.update({
  id: '/workbook-form',
  path: '/workbook-form',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbookSheetRoute = WorkbookSheetRouteImport.update({
  id: '/workbook-sheet',
  path: '/workbook-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const RootLayoutAboutRoute = RootLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RootLayoutRoute,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adjustment-sheet': typeof AdjustmentSheetRoute
  '/basic-grid': typeof BasicGridRoute
  '/grid': typeof GridRoute
  '/large-workbook': typeof LargeWorkbookRoute
  '/session-sheet': typeof SessionSheetRoute
  '/workbook-closing': typeof WorkbookClosingRoute
  '/workbook-form': typeof WorkbookFormRoute
  '/workbook-sheet': typeof WorkbookSheetRoute
  '/about': typeof RootLayoutAboutRoute
  '/files/$': typeof FilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adjustment-sheet': typeof AdjustmentSheetRoute
  '/basic-grid': typeof BasicGridRoute
  '/grid': typeof GridRoute
  '/large-workbook': typeof LargeWorkbookRoute
  '/session-sheet': typeof SessionSheetRoute
  '/workbook-closing': typeof WorkbookClosingRoute
  '/workbook-form': typeof WorkbookFormRoute
  '/workbook-sheet': typeof WorkbookSheetRoute
  '/about': typeof RootLayoutAboutRoute
  '/files/$': typeof FilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_rootLayout': typeof RootLayoutRouteWithChildren
  '/adjustment-sheet': typeof AdjustmentSheetRoute
  '/basic-grid': typeof BasicGridRoute
  '/grid': typeof GridRoute
  '/large-workbook': typeof LargeWorkbookRoute
  '/session-sheet': typeof SessionSheetRoute
  '/workbook-closing': typeof WorkbookClosingRoute
  '/workbook-form': typeof WorkbookFormRoute
  '/workbook-sheet': typeof WorkbookSheetRoute
  '/_rootLayout/about': typeof RootLayoutAboutRoute
  '/files/$': typeof FilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adjustment-sheet'
    | '/basic-grid'
    | '/grid'
    | '/large-workbook'
    | '/session-sheet'
    | '/workbook-closing'
    | '/workbook-form'
    | '/workbook-sheet'
    | '/about'
    | '/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adjustment-sheet'
    | '/basic-grid'
    | '/grid'
    | '/large-workbook'
    | '/session-sheet'
    | '/workbook-closing'
    | '/workbook-form'
    | '/workbook-sheet'
    | '/about'
    | '/files/$'
  id:
    | '__root__'
    | '/'
    | '/_rootLayout'
    | '/adjustment-sheet'
    | '/basic-grid'
    | '/grid'
    | '/large-workbook'
    | '/session-sheet'
    | '/workbook-closing'
    | '/workbook-form'
    | '/workbook-sheet'
    | '/_rootLayout/about'
    | '/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RootLayoutRoute: typeof RootLayoutRouteWithChildren
  AdjustmentSheetRoute: typeof AdjustmentSheetRoute
  BasicGridRoute: typeof BasicGridRoute
  GridRoute: typeof GridRoute
  LargeWorkbookRoute: typeof LargeWorkbookRoute
  SessionSheetRoute: typeof SessionSheetRoute
  WorkbookClosingRoute: typeof WorkbookClosingRoute
  WorkbookFormRoute: typeof WorkbookFormRoute
  WorkbookSheetRoute: typeof WorkbookSheetRoute
  FilesSplatRoute: typeof FilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout': {
      id: '/_rootLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjustment-sheet': {
      id: '/adjustment-sheet'
      path: '/adjustment-sheet'
      fullPath: '/adjustment-sheet'
      preLoaderRoute: typeof AdjustmentSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-grid': {
      id: '/basic-grid'
      path: '/basic-grid'
      fullPath: '/basic-grid'
      preLoaderRoute: typeof BasicGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/large-workbook': {
      id: '/large-workbook'
      path: '/large-workbook'
      fullPath: '/large-workbook'
      preLoaderRoute: typeof LargeWorkbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-sheet': {
      id: '/session-sheet'
      path: '/session-sheet'
      fullPath: '/session-sheet'
      preLoaderRoute: typeof SessionSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbook-closing': {
      id: '/workbook-closing'
      path: '/workbook-closing'
      fullPath: '/workbook-closing'
      preLoaderRoute: typeof WorkbookClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbook-form': {
      id: '/workbook-form'
      path: '/workbook-form'
      fullPath: '/workbook-form'
      preLoaderRoute: typeof WorkbookFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbook-sheet': {
      id: '/workbook-sheet'
      path: '/workbook-sheet'
      fullPath: '/workbook-sheet'
      preLoaderRoute: typeof WorkbookSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rootLayout/about': {
      id: '/_rootLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof RootLayoutAboutRouteImport
      parentRoute: typeof RootLayoutRoute
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RootLayoutRouteChildren {
  RootLayoutAboutRoute: typeof RootLayoutAboutRoute
}

const RootLayoutRouteChildren: RootLayoutRouteChildren = {
  RootLayoutAboutRoute: RootLayoutAboutRoute,
}

const RootLayoutRouteWithChildren = RootLayoutRoute._addFileChildren(
  RootLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RootLayoutRoute: RootLayoutRouteWithChildren,
  AdjustmentSheetRoute: AdjustmentSheetRoute,
  BasicGridRoute: BasicGridRoute,
  GridRoute: GridRoute,
  LargeWorkbookRoute: LargeWorkbookRoute,
  SessionSheetRoute: SessionSheetRoute,
  WorkbookClosingRoute: WorkbookClosingRoute,
  WorkbookFormRoute: WorkbookFormRoute,
  WorkbookSheetRoute: WorkbookSheetRoute,
  FilesSplatRoute: FilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
