services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: pnpm-lock.yaml
        - action: rebuild
          path: pnpm-workspace.yaml
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .git/
            - dist/