import type { Product } from './types'

export const products: Product[] = [
  {
    product: 'Atlas Notebook',
    category: 'Stationery',
    status: 'In stock',
    units: 184,
    price: 18,
    lastUpdated: '2026-09-03',
  },
  {
    product: 'Field Pack',
    category: 'Travel',
    status: 'Low stock',
    units: 24,
    price: 96,
    lastUpdated: '2026-09-05',
  },
  {
    product: 'Quartz Bottle',
    category: 'Kitchen',
    status: 'In stock',
    units: 312,
    price: 28,
    lastUpdated: '2026-09-06',
  },
  {
    product: 'Signal Lamp',
    category: 'Outdoors',
    status: 'Backordered',
    units: 0,
    price: 74,
    lastUpdated: '2026-09-08',
  },
  {
    product: 'Cedar Chair',
    category: 'Furniture',
    status: 'Low stock',
    units: 12,
    price: 240,
    lastUpdated: '2026-09-09',
  },
  {
    product: 'Mica Headphones',
    category: 'Audio',
    status: 'In stock',
    units: 86,
    price: 129,
    lastUpdated: '2026-09-10',
  },
  {
    product: 'Orbit Lamp',
    category: 'Lighting',
    status: 'In stock',
    units: 58,
    price: 145,
    lastUpdated: '2026-09-11',
  },
  {
    product: 'Canvas Tote',
    category: 'Travel',
    status: 'In stock',
    units: 226,
    price: 32,
    lastUpdated: '2026-09-12',
  },
  {
    product: 'Current Keyboard',
    category: 'Audio',
    status: 'Backordered',
    units: 0,
    price: 110,
    lastUpdated: '2026-09-13',
  },
  {
    product: 'North Mug',
    category: 'Kitchen',
    status: 'In stock',
    units: 410,
    price: 22,
    lastUpdated: '2026-09-14',
  },
  {
    product: 'Lumen Desk',
    category: 'Furniture',
    status: 'Low stock',
    units: 9,
    price: 380,
    lastUpdated: '2026-09-15',
  },
  {
    product: 'Pine Marker Set',
    category: 'Stationery',
    status: 'In stock',
    units: 142,
    price: 14,
    lastUpdated: '2026-09-16',
  },
]
