/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BasicGridRouteImport } from './routes/basic-grid'
import { Route as GridRouteImport } from './routes/grid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicGridRoute = BasicGridRouteImport.update({
  id: '/basic-grid',
  path: '/basic-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-grid': typeof BasicGridRoute
  '/grid': typeof GridRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-grid': typeof BasicGridRoute
  '/grid': typeof GridRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-grid': typeof BasicGridRoute
  '/grid': typeof GridRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/basic-grid' | '/grid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/basic-grid' | '/grid'
  id: '__root__' | '/' | '/basic-grid' | '/grid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicGridRoute: typeof BasicGridRoute
  GridRoute: typeof GridRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-grid': {
      id: '/basic-grid'
      path: '/basic-grid'
      fullPath: '/basic-grid'
      preLoaderRoute: typeof BasicGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicGridRoute: BasicGridRoute,
  GridRoute: GridRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
